name: houseman
version: 0.1.0
synopsis: A Haskell implementation of Foreman
maintainer: Daisuke Fujimura <me@fujmuradaisuke.com>
license: MIT
github: fujimura/houseman
category: Development

ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N

dependencies:
  - base
  - bytestring
  - text
  - unix
  - process
  - trifecta
  - parsers
  - time
  - optparse-generic
  - dotenv
  - directory
  - streaming-commons
  - mtl
  - io-streams
  - tagged

library:
  source-dirs: src

executables:
  houseman:
    main: Main.hs
    source-dirs: app
    dependencies:
      - houseman

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - temporary
      - silently
      - mockery
      - interpolate
      - QuickCheck
