name: houseman
version: 0.0.1
synopsis: TBD
maintainer: Daisuke Fujimura <me@fujmuradaisuke.com>
license: MIT
github: fujimura/houseman
category: Development

ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - text
  - unix
  - process
  - trifecta
  - parsers
  - time
  - optparse-generic
  - dotenv
  - directory
  - streaming-commons
  - mtl
  - io-streams

library:
  source-dirs: src

executables:
  houseman:
    main: Main.hs
    source-dirs: app
    dependencies:
      - houseman

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - temporary
      - silently
      - mockery >= 0.3
      - interpolate
      - QuickCheck
