on: [push]
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['9.0.1', '8.10.7']
        cabal: ['3.4.0.0']
    name: Run test on GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal build --only-dependencies --enable-tests
      - run: cabal test --test-show-details=direct
    name: Build on GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal build
